### ISSUE TITLE
Unsupported query_type CREATEPROCEDURE work around options?

### ISSUE THREAD

**Issue by samLozier** [macbre/sql-metadata#212] opened 2021-08-17 19:15 UTC
I'm trying to parse the text of a number of MSSQL stored procedures and have been getting this error. Is there a built in method  that will allow me to extract referenced table names and aliases? 

I've come up with this rather hacky work around, but I thought there might be a better way

```from sql_metadata import Parser

sql="""

CREATE PROCEDURE [schem].[test_proc] @report_date date 

AS

insert into DataStore.schem.othertable
select TOP 100 * from DataStore.schem.bigtable
;

"""
# this raises the error
parser = Parser(sql=sql)
print(parser.tables)


# this correctly extracts table names
def remove_proc_def(sql):
    if "CREATE PROCEDURE" in sql.upper():
        sql_split = sql.split("AS",1 )
        proc_def=sql_split[0]
        sql=sql_split[1]
    else:
        proc_def=""
        sql=sql
    return proc_def, sql


parser = Parser(sql=remove_proc_def(sql)[1])
print(parser.tables)

```

**Comment by collerek** [comment] 2021-08-18 08:45
The alternative would be to probably add support for creating procedures 😄 

The exception was added intentionally as despite SQL being structured when you take into consideration all dialects, deeply nested subqueries, etc. parsing it to extract columns and tables is already quite complicated.

There is a very high chance that an unsupported query type will not behave properly, so to give explicit feedback we introduced this check.

As for the workaround, you probably are as close as it gets. 
But note that in your scenario the procedure definition needs to be supported too. 

One of the reasons we do not support procedures is that procedures are basically too complex.
You can have full programs written in tsql with loops, variables, transactions etc.

As of now, `sql-metadata` focuses more on crud SQL queries (select/insert/update/delete), which might change in the future, but given the complexity, I would assume it won't happen in the nearest future.

**Comment by macbre** [comment] 2021-08-18 11:08
I second @collerek's opinion. We want to limit the features set of `sql-metadata` to the most basic / typical SQL use cases. SQL procedures are wild beast which would add way too much complexity to this project.

**Comment by collerek** [comment] 2021-08-20 13:11
Since @macbre confirmed I guess that's all we can provide you with as of now, so I will close this issue.

**Closed by collerek** 2021-08-20 13:11 UTC
