### ISSUE TITLE
Exception when parsing a valid query with a comment

### ISSUE THREAD

**Issue by lexarx** [macbre/sql-metadata#297] opened 2022-03-11 17:53 UTC
Expected behavior

```
assert Parser("""
    with foo as (select * from bar)
    ------------ comment
    select 1 as baz
""").tables == ["bar"]
```

Actual behavior

> AttributeError: 'NoneType' object has no attribute 'normalized'

**Comment by macbre** [comment] 2022-04-26 11:19
Duplicate of #311, will be fixed there. Thanks for reporting!

**Closed by macbre** 2022-04-26 11:19 UTC
Labels: bug
